### ISSUE TITLE
can this operator work with empty pvs instead of disks?

### ISSUE THREAD

**Issue by zfrhv** [openshift/lvm-operator#315]
hello, we have many snos and each one has only one disk of 1 tb.
is there any way for us to make this operator work if we split the disk into multiple partitions instead of buying new disks?

**Comment by suleymanakbas91** [comment]
Hi @zfrhv, this is already possible by specifying `deviceSelector.paths` option under deviceClasses like: 

```
apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: my-lvmcluster
spec:
  storage:
    deviceClasses:
    - name: vg1
      thinPoolConfig:
        name: thin-pool-1
        sizePercent: 90
        overprovisionRatio: 10
      deviceSelector:
        paths:
        - /dev/nvme1n1p1 
        - /dev/nvme1n1p2
```
This will create a StorageClass which will use the specified partitions to create a volume group. 

You can also specify multiple device classes with paths pointing to different partitions like:
```
apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: my-lvmcluster
spec:
  storage:
    deviceClasses:
    - name: vg1
      thinPoolConfig:
        name: thin-pool-1
        sizePercent: 90
        overprovisionRatio: 10
      deviceSelector:
        paths:
        - /dev/nvme1n1p1
      default: true
    - name: vg2
      thinPoolConfig:
        name: thin-pool-2
        sizePercent: 90
        overprovisionRatio: 10
      deviceSelector:
        paths:
        - /dev/nvme1n1p2
```

This will then create two different StorageClasses making use of the corresponding partitions specified under `paths`.

**Comment by zfrhv** [comment]
thank you very much for the detailed explanation!
we will try it !

**Comment by zfrhv** [comment]
hello,
i tried to configure:
```yaml
deviceSelector:
  paths:
  - /dev/nvme0n1p5
```
but after applying the yaml it returns to:
```yaml
deviceSelector: {}
```
seems like the operator overrides that field to empty object.

nothing in the logs, nothing happens
im using ODF LVM 4.10.7

should i open an issue or try to upgrade the operator?
